# OIDC confidential secret for your client
client_id: "PASTE_YOUR_OIDC_CLIENT_ID_HERE"
client_secret: "PASTE_YOUR_OIDC_CLIENT_SECRET_HERE"

# SMTP password (only if enable_email: true)
smtp:
  smtp_password: "PASTE_YOUR_SMTP_PASSWORD_HERE"

# The OIDC preferred_username you want to ensure exists as a local UNIX account
preferred_username: "user"

# (Optional) Other local users you also want to ensure exist
extra_local_users:
  - "im"

jump_user_pubkey: "pubkey"
